theme: jekyll-theme-slate
title: "Applikačné programovanie v C++"
description: Nezaradené texty v nikdy nekončiacom vývoji
url: htttp://cppseminar.github.io
author:
  name: Peter Koscelanský
  email: koscelansky@live.com
  github: koscelansky